#!/usr/bin/env bash
# Prints the Homebrew cask for Scribe (Casks/scribe.rb in
# varijkapil13/homebrew-tap) for a given release.
#
#   packaging/homebrew/render-cask.sh 0.1.0 <sha256 of Scribe-v0.1.0.zip>
#
# The release workflow runs this after publishing a GitHub Release and pushes
# the result to the tap; it can also be run by hand.
set -euo pipefail

VERSION="${1:?usage: render-cask.sh VERSION SHA256}"
SHA256="${2:?usage: render-cask.sh VERSION SHA256}"

cat <<CASK
# Generated by packaging/homebrew/render-cask.sh in varijkapil13/scribe.
# Updated automatically on each release; edit the script, not this file.
cask "scribe" do
  version "${VERSION}"
  sha256 "${SHA256}"

  url "https://github.com/varijkapil13/scribe/releases/download/v#{version}/Scribe-v#{version}.zip"
  name "Scribe"
  desc "On-device meeting transcription, notes and tasks"
  homepage "https://github.com/varijkapil13/scribe"

  livecheck do
    url :url
    strategy :github_latest
  end

  # Scribe updates itself with Sparkle (Settings › About › Updates), so
  # brew upgrade skips it unless run with --greedy; the app also reads this
  # flag to decide whether to leave updates to Homebrew.
  auto_updates true

  # Apple Silicon only. The app itself requires macOS 27 (LSMinimumSystemVersion).
  depends_on arch: :arm64

  app "Scribe.app"

  # Release builds without a Developer ID are ad-hoc signed, not notarized,
  # so Gatekeeper would block the first launch. Clear the quarantine flag that
  # the download added, the same way the saral cask does (harmless for
  # notarized builds).
  postflight do
    system_command "/usr/bin/xattr",
                   args:         ["-dr", "com.apple.quarantine", "#{appdir}/Scribe.app"],
                   must_succeed: false
  end

  uninstall quit: "com.varij.scribe"

  # App data only. Your notes vault (~/Documents/Scribe by default, or wherever
  # you moved it) is never removed.
  zap trash: [
    "~/Library/Application Support/Scribe",
    "~/Library/Caches/com.varij.scribe",
    "~/Library/HTTPStorages/com.varij.scribe",
    "~/Library/Preferences/com.varij.scribe.plist",
    "~/Library/Saved Application State/com.varij.scribe.savedState",
    "~/Library/WebKit/com.varij.scribe",
  ]
end
CASK
